config/routes.rb
Rails.application.routes.draw do
  resources :sub_types
  resources :type_equipaments
  resources :meals
  namespace :dashboard do
    resources :admin, except:[:show]
    get 'admins',to:'admin#index'
    post 'admins',to:'admin#create'
  end

  resources :calculations
  resources :equipaments
  resources :services do
    resources :proposals
  end
  resources :services do
    resources :proposal_hour_extras
  end
  resources :rotations
  resources :roles
  resources :services
  resources :periods
  resources :cities
  resources :companies
  devise_for :admins,  :skip => [:registrations]
  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/equipament.rb
class Equipament < ActiveRecord::Base
	belongs_to :type_equipament
	belongs_to :sub_type
	has_many :proposal_equipaments
  #has_many :proposals, :through => :proposal_equipaments

  def name_select
    "#{name_equipament} - Ddp:#{depreciacao} - Val:R$ #{valor} - Nº#{id}"
  end
  before_save :atualiza_data_do_preco


private
	def atualiza_data_do_preco
		if valor_changed?
			if(valor_change[0] != valor_change[1])
				self.updated_date_valor = DateTime.now
			end
		end
		##valor_change[0] #Antigo
		##valor_change[1] #Novo
		###update_column(:updated_date_valor,(updatedDateValor))
	end

end

app/controllers/equipaments_controller.rb
class EquipamentsController < ApplicationMainController
	before_action :set_equipament, only: [:show, :edit, :update, :destroy]

	# GET /equipaments
	# GET /equipaments.json
	def index
		if  current_admin.full_access? || current_admin.partial_access?
			@equipaments = Equipament.all
		else
			redirect_to "/404.html"# configurar pagina 403
		end
	end

	# GET /equipaments/1
	# GET /equipaments/1.json
	def show
		select_type
		select_sub_type
		unless current_admin.full_access? || current_admin.partial_access?
		  redirect_to "/404.html"# configurar pagina 403
		end
	end

	# GET /equipaments/new
	def new
		select_type
		select_sub_type
		if  current_admin.full_access? || current_admin.partial_access?
			@equipament = Equipament.new
		else
			redirect_to "/404.html"# configurar pagina 403
		end
	end

	# GET /equipaments/1/edit
	def edit
		select_type
		select_sub_type
		unless current_admin.full_access? || current_admin.partial_access?
			redirect_to "/404.html"# configurar pagina 403
		end
	end

	# POST /equipaments
	# POST /equipaments.json
	def create
		@equipament = Equipament.new(equipament_params)

		respond_to do |format|
			if @equipament.save
				format.html { redirect_to @equipament, notice: 'Equipament was successfully created.' }
				format.json { render :show, status: :created, location: @equipament }
			else
				format.html { render :new }
				format.json { render json: @equipament.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /equipaments/1
	# PATCH/PUT /equipaments/1.json
	def update
		respond_to do |format|
			if @equipament.update(equipament_params)
				format.html { redirect_to @equipament, notice: 'Equipament was successfully updated.' }
				format.json { render :show, status: :ok, location: @equipament }
			else
				format.html { render :edit }
				format.json { render json: @equipament.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /equipaments/1
	# DELETE /equipaments/1.json
	def destroy
		@equipament.destroy
		respond_to do |format|
			format.html { redirect_to equipaments_url, notice: 'Equipament was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def select_type
			@select_all_type = TypeEquipament.all
		end
		def select_sub_type
			@select_all_sub_type = SubType.all
		end

		def set_equipament
			@equipament = Equipament.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def equipament_params
			delocalize_config = { :valor => :number }
			params.require(:equipament).permit( :name_equipament,:fornecedor ,:marca_mod ,:rec_manutencao ,:obs_equipament ,
																					:valor, :depreciacao, :proposal_id, :type_equipament_id, :sub_type_id, :control_print).delocalize(delocalize_config)
		end
end

app/helpers/equipaments_helper.rb
module EquipamentsHelper
end

app/views/equipaments/_form.html.erb
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			Formulario de criação
		</div>

		<div class="panel-body">
			<div class="col-lg-12">
				<%= form_for(@equipament) do |f| %>
				<% if @equipament.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@equipament.errors.count, "error") %> prohibited this equipament from being saved:</h2>

					<ul>
						<% @equipament.errors.full_messages.each do |message| %>
						<li><%= message %></li>
						<% end %>
					</ul>
				</div>
				<% end %>      
				<div class="inline">
					<div class="row">
						<div class="col-sm-4">
							<div class="field">
								<strong>Nome do Equipamento</strong><br>
								<%= f.text_field :name_equipament, class:'form-control', placeholder:'Nome do Equipamento ou acessorios' %>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="field">
								<strong>Valor do Equipamento</strong><br>
								<%= f.text_field :valor,:value => number_with_precision(f.object.valor,precision: 2, locale: :"pt-BR"), class:'form-control', placeholder:'Valor do Equipamento ou acessorios' %>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="field">
								<strong>Depreciação do Equipamento</strong><br>
								<%= f.text_field :depreciacao, class:'form-control', placeholder:'Deprecição' %>
							</div>
						</div>
					</div>
				</div> 
				<div class="inline">
					<div class="row">
						<div class="col-sm-3">
							<div class="field">
								<strong>Categora Principal</strong><br>
								<%= collection_select(:equipament, :type_equipament_id,@select_all_type, :id, :name_type,{},class:'form-control') %>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="field">
								<strong>Sub categoria</strong><br>
								<%= collection_select(:equipament, :sub_type_id, @select_all_sub_type, :id, :name_select2,{},class:'form-control') %>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="field">
								<strong>Requer Manutenção</strong><br>
								<%= f.select :rec_manutencao, options_for_select([["Não",0],["Sim",1]], @equipament.rec_manutencao),{},class:'form-control' %>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="field">
								<strong>Fornecedor</strong><br>
								<%= f.text_field :fornecedor, class:'form-control', placeholder:'' %>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="field">
								<strong>Marca ou modelo</strong><br>
								<%= f.text_field :marca_mod, class:'form-control', placeholder:'' %>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="field">
								<strong>Exibir na impreção pricipal?</strong><br>
								<%= f.select :control_print, options_for_select([["Não",0],["Sim",1]], @equipament.control_print),{},class:'form-control' %>
							</div>
						</div>
					</div>
				</div>
				<div class="inline">
					<div class="row">
						<div class="col-sm-6">
							<div class="field">
								<strong>Obs. Equipamento</strong><br>
								<%= f.text_area(:obs_equipament,size: "50x10",class:'form-control' ) %>
							</div>
						</div>
					</div>
				</div>
					<div class="actions">
						<button type="submit" class="btn btn-outline btn-success">Salvar</button>
					</div>
					<% end %>

		</div>
	</div>
</div>

app/views/equipaments/edit.html.erb
<%= link_to equipaments_path,class:"btn btn-outline btn-success pull-right topHeader", type:"button" do %>
  <i class="fa fa-clipboard fa-fw"></i> Voltar
<% end %>   
<%= link_to @equipament,class:"btn btn-outline btn-success pull-right topHeader", type:"button" do %>
  <i class="fa fa-clipboard fa-fw"></i> Exibir
<% end %>
<h1  class="page-header topHeader">Editando equipamento ou acessorio</h1>

<%= render 'form' %>

app/views/equipaments/index.html.erb
<h1 class="page-header topHeader">Lista de Equipamentos e Acessorios
		<%= link_to sub_types_path,class:"btn btn-default dropdown-toggle pull-right", type:"button" do %>
		Nova Categoria-Sub
		<% end %>
		<%= link_to type_equipaments_path,class:"btn btn-default dropdown-toggle pull-right", type:"button" do %>
		Nova Categoria  
		<% end %>
</h1>
<div class="panel panel-default">
	<div class="panel-heading">
		<strong>Equipamentos e Acessorios</strong>
		<%= link_to new_equipament_path,class:"btn btn-success dropdown-toggle pull-right botton-barra", type:"button" do %>
		Novo Equipameto ou Acessorios  
		<% end %>    
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table id="equipamentTab" class="table table-striped table-bordered table-hover" style="overflow: scroll;width: 1800px;">
				<thead>
					<tr>
						<th style="width:8px;text-align:center; ">#</th>
						<th >Equipamento</th>
						<th style="width: 126px;padding-left: 5px;padding-right: 5px;">Categora Principal</th>
						<th style="width: 126px;padding-left: 5px;padding-right: 5px;">Sub-categoria</th>
						<th>Valor</th>
						<th>Dpr</th>
						<th style="width: 137px; text-align: center;">valor atualizado</th>
						<th style="width: 600px;">Observações</th>
						<th colspan="1" class="espaco3E" style="width: 71px"></th>
					</tr>
				</thead>
				<tbody>
					<% @equipaments.each do |equipament| %>
					<tr>
						<div class="panel panel-default" style="display:none">
						</div>

						<td style="text-align:center;"><%= equipament.id %></td>
						<td><%= equipament.name_equipament %></td>
						<td><%= equipament.type_equipament.name_type %></td>
						<td><%= equipament.sub_type.name_sub_type %></td>
						<td><%= number_to_currency(equipament.valor) %></td>
						<td style="text-align:center;"><%= (equipament.depreciacao).round(0) %></td>
						<td style="padding-right: 0px;padding-left: 2px;text-align: center;"><%= update_date(equipament.updated_date_valor) %></td>
						<td><%= equipament.obs_equipament %></td>
						<td>
							<%= link_to equipament,class:"btn btn-default btn-sm ", type:"button",title:"Exibir" do %>
								<i class="fa fa-search"></i>
							<% end %>
							<%= link_to edit_equipament_path(equipament),class:"btn btn-default btn-sm ", type:" button",title:"Editar" do %>
								<i class="fa fa-edit"></i>
							<% end %>
							<!--<#%= link_to equipament, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-default btn-danger btn-sm ", type:"button",title:"Excluir" do %>
								<i class="fa fa-trash-o"></i>
							<#% end %>-->
						</td>
					</tr> 
					<% end %>
				</tbody>
			</table>
		</div>
		<!-- /.table-responsive -->
	</div>
	<!-- /.panel-body -->
</div>

app/views/equipaments/new.html.erb
<%= link_to equipaments_path,class:"btn btn-outline btn-success pull-right topHeader", type:"button" do %>
  <i class="fa fa-clipboard fa-fw"></i> Voltar
<% end %>
<h1 class="page-header topHeader">Novo Equipamento ou Acessorio</h1>

<%= render 'form' %>

app/views/equipaments/show.html.erb
</br>
<div class="panel panel-default">
	<div class="panel-heading">
		<strong>Equipamento ou Acessorio</strong>

	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover">
				<thead>
					<tr>
						<th style="width: 168px;">Nome do Campo</th>
						<th>Valor do campo</th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<td><strong>Name equipament:</strong></td>
						<td><%= @equipament.name_equipament %></td>
					</tr>

					<tr>
						<td><strong>Valor:</strong></td>
						<td><%= @equipament.valor %></td>
					</tr>

					<tr>
						<td><strong>Categora Principal:</strong></td>
						<td><%= @equipament.type_equipament.name_type %></td>
					</tr>
					<tr>
						<td><strong>Sub-categoria:</strong></td>
						<td><%= @equipament.sub_type.name_sub_type %></td>
					</tr>
					<tr>
						<td><strong>Requer Manutenção:</strong></td>
						<td><%if @equipament.rec_manutencao==1 %>
									Sim
								<%elsif @equipament.rec_manutencao==0 %>
									Não
								<% else %>
									Não definido
								<% end %>
						</td>
					</tr>
					<tr>
						<td><strong>Fornecedor:</strong></td>
						<td><%= @equipament.fornecedor %></td>
					</tr>
					<tr>
						<td><strong>Marca ou modelo:</strong></td>
						<td><%= @equipament.marca_mod %></td>
					</tr>
					<tr>
						<td><strong>Obs. Equipamento:</strong></td>
						<td><%= @equipament.obs_equipament %></td>
					</tr>

				</tbody>
			</table>
			<%= link_to equipaments_path,class:"btn btn-default btn-sm ajusteButton", type:"button" do %>
			<i class="fa fa-arrow-left"></i> Voltar
			<% end %>
			<%= link_to edit_equipament_path(@equipament),class:"btn btn-default btn-sm ajusteButton", type:"button" do %>
			<i class="fa fa-edit"></i> Editar
			<% end %>
		</div>
		<!-- /.table-responsive -->
	</div>
	<!-- /.panel-body -->
</div>