config/routes.rb
Rails.application.routes.draw do
  resources :sub_types
  resources :type_equipaments
  resources :meals
  namespace :dashboard do
    resources :admin, except:[:show]
    get 'admins',to:'admin#index'
    post 'admins',to:'admin#create'
  end

  resources :calculations
  resources :equipaments
  resources :services do
    resources :proposals
  end
  resources :services do
    resources :proposal_hour_extras
  end
  resources :rotations
  resources :roles
  resources :services
  resources :periods
  resources :cities
  resources :companies
  devise_for :admins,  :skip => [:registrations]
  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/proposal_equipament.rb
class ProposalEquipament < ActiveRecord::Base
	belongs_to :equipament
	belongs_to :proposal
	belongs_to :type_equipament
	belongs_to :sub_type

	accepts_nested_attributes_for :equipament, reject_if: :all_blank, allow_destroy:true

	after_save :preeche_capos_vazios

	validates :type_equipament_id, numericality: { only_integer: true,  message: "should happen once per year"}

private
	def preeche_capos_vazios
		if self.quantidade.nil?
			self.quantidade = 0
		end
		unless (depreciacao_aux.nil? )
			depreciacaoValida = depreciacao_aux
		else
			depreciacaoValida = equipament.depreciacao.to_f
		end

		if valorEquipSub == 0 || valorEquipSub.nil?
			valorEquipament = equipament.valor.to_f
		else
			valorEquipament = valorEquipSub.to_f
		end

		depreciado = (quantidade*(valorEquipament.to_f / (depreciacaoValida.to_f == 0.0 ? 1 : depreciacaoValida.to_f))).round(2)
#   depreciado = (quantidade*(self.equipament.valor.to_f / (depreciacaoValida.to_f == 0.0 ? 1 : depreciacaoValida.to_f))).round(2)

		nameEquipament = self.equipament.name_equipament
		update_column(:name_equipament,(nameEquipament))
		update_column(:depreciacao_valida, (depreciacaoValida))
		update_column(:quantidade, (self.quantidade))
		update_column(:valor_equipament, (valorEquipament))
		update_column(:valor_depreciado, (depreciado))
		
	end
end

app/controllers/proposal_equipaments_controller.rb
class ProposalEquipamentsController < ApplicationMainController
  before_action :set_proposal_equipament, only: [:show, :edit, :update, :destroy]
  
  # GET /proposal_equipaments
  # GET /proposal_equipaments.json
  def index
    #@proposal_equipaments = ProposalEquipament.all
  end

  # GET /proposal_equipaments/1
  # GET /proposal_equipaments/1.json
  def show
  end

  # GET /proposal_equipaments/new
  def new
    @proposal_equipament = ProposalEquipament.new
  end

  # GET /proposal_equipaments/1/edit
  def edit
  end

  # POST /proposal_equipaments
  # POST /proposal_equipaments.json
  def create
    @proposal_equipament = ProposalEquipament.new(proposal_equipament_params)

    respond_to do |format|
      if @proposal_equipament.save
        format.html { redirect_to @proposal_equipament, notice: 'Proposal equipament was successfully created.' }
        format.json { render :show, status: :created, location: @proposal_equipament }
      else
        format.html { render :new }
        format.json { render json: @proposal_equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposal_equipaments/1
  # PATCH/PUT /proposal_equipaments/1.json
  def update
    puts "teste sub "+@proposal_equipament.valorEquipSub
    respond_to do |format|
      if @proposal_equipament.update(proposal_equipament_params)
        format.html { redirect_to @proposal_equipament, notice: 'Proposal equipament was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposal_equipament }
      else
        format.html { render :edit }
        format.json { render json: @proposal_equipament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposal_equipaments/1
  # DELETE /proposal_equipaments/1.json
  def destroy
    @proposal_equipament.destroy
    respond_to do |format|
      format.html { redirect_to proposal_equipaments_url, notice: 'Proposal equipament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal_equipament
      @proposal_equipament = ProposalEquipament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_equipament_params
      delocalize_config = { :valorEquipSub => :number}
      params.require(:proposal_equipament).permit(:equipament_id, :proposal_id, :quantidade, :depreciacao_aux, :name_equipament, :valorEquipSub, :valor_equipament).delocalize(delocalize_config)
    end
end

app/helpers/proposal_equipaments_helper.rb
module ProposalEquipamentsHelper
end

app/views/proposal_equipaments/_form.html.erb
<%= form_for(@proposal_equipament) do |f| %>
  <% if @proposal_equipament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proposal_equipament.errors.count, "error") %> prohibited this proposal_equipament from being saved:</h2>

      <ul>
      <% @proposal_equipament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :equipament_id %><br>
    <%= f.text_field :equipament_id %>
  </div>
  <div class="field">
    <%= f.label :proposal_id %><br>
    <%= f.text_field :proposal_id %>
  </div>
  <div class="field">
    <%= f.label :quantidade %><br>
    <%= f.text_field :quantidade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proposal_equipaments/edit.html.erb
<h1>Editing Proposal Equipament</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal_equipament %> |
<%= link_to 'Back', proposal_equipaments_path %>

app/views/proposal_equipaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Proposal Equipaments</h1>

<table>
  <thead>
    <tr>
      <th>Equipament</th>
      <th>Proposal</th>
      <th>Quantidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proposal_equipaments.each do |proposal_equipament| %>
      <tr>
        <td><%= proposal_equipament.equipament %></td>
        <td><%= proposal_equipament.proposal %></td>
        <td><%= proposal_equipament.quantidade %></td>
        <td><%= link_to 'Show', proposal_equipament %></td>
        <td><%= link_to 'Edit', edit_proposal_equipament_path(proposal_equipament) %></td>
        <!--td><#%= link_to 'Destroy', proposal_equipament, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proposal equipament', new_proposal_equipament_path %>

app/views/proposal_equipaments/new.html.erb
<h1>New Proposal Equipament</h1>

<%= render 'form' %>

<%= link_to 'Back', proposal_equipaments_path %>

app/views/proposal_equipaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Equipament:</strong>
  <%= @proposal_equipament.equipament %>
</p>

<p>
  <strong>Proposal:</strong>
  <%= @proposal_equipament.proposal %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @proposal_equipament.quantidade %>
</p>

<%= link_to 'Edit', edit_proposal_equipament_path(@proposal_equipament) %> |
<%= link_to 'Back', proposal_equipaments_path %>