config/routes.rb
Rails.application.routes.draw do
  resources :sub_types
  resources :type_equipaments
  resources :meals
  namespace :dashboard do
    resources :admin, except:[:show]
    get 'admins',to:'admin#index'
    post 'admins',to:'admin#create'
  end

  resources :calculations
  resources :equipaments
  resources :services do
    resources :proposals
  end
  resources :services do
    resources :proposal_hour_extras
  end
  resources :rotations
  resources :roles
  resources :services
  resources :periods
  resources :cities
  resources :companies
  devise_for :admins,  :skip => [:registrations]
  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/controllers/sub_types_controller.rb
class SubTypesController < ApplicationMainController
  before_action :set_sub_type, only: [:show, :edit, :update, :destroy]

  # GET /sub_types
  # GET /sub_types.json
  def index
    @sub_types = SubType.all
  end

  # GET /sub_types/1
  # GET /sub_types/1.json
  def show
  end

  # GET /sub_types/new
  def new
    @sub_type = SubType.new
    type_equipament
  end

  # GET /sub_types/1/edit
  def edit
    type_equipament
  end

  # POST /sub_types
  # POST /sub_types.json
  def create
    @sub_type = SubType.new(sub_type_params)

    respond_to do |format|
      if @sub_type.save
        format.html { redirect_to sub_types_path, notice: 'Sub type was successfully created.' }
        format.json { render :show, status: :created, location: @sub_type }
      else
        format.html { render :new }
        format.json { render json: @sub_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_types/1
  # PATCH/PUT /sub_types/1.json
  def update
    respond_to do |format|
      if @sub_type.update(sub_type_params)
        format.html { redirect_to sub_types_path, notice: 'Sub type was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_type }
      else
        format.html { render :edit }
        format.json { render json: @sub_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_types/1
  # DELETE /sub_types/1.json
  def destroy
    @sub_type.destroy
    respond_to do |format|
      format.html { redirect_to sub_types_url, notice: 'Sub type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def type_equipament
      @select_all_type = TypeEquipament.all
    end
    def set_sub_type
      @sub_type = SubType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_type_params
      params.require(:sub_type).permit(:name_sub_type)
    end
end

app/helpers/sub_types_helper.rb
module SubTypesHelper
end

app/views/sub_types/_form.html.erb
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			Formulario
		</div>

		<div class="panel-body">
			<div class="col-lg-12">
				<%= form_for(@sub_type) do |f| %>
				<% if @sub_type.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@sub_type.errors.count, "error") %> prohibited this sub_type from being saved:</h2>
					<ul>
						<% @sub_type.errors.full_messages.each do |message| %>
						<li><%= message %></li>
						<% end %>
					</ul>
				</div>
				<% end %>
				<div class="inline">
					<div class="row">
						<div class="col-sm-4">
							<div class="field">
								<strong>Sub-categoria de equipamento</strong><br>
								<%= f.text_field :name_sub_type,class:'form-control' %>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="field">
								<strong>Categora Principal</strong><br>
								<%= collection_select(:sub_type, :type_equipament_id,@select_all_type, :id, :name_type,{},class:'form-control') %>
							</div>
						</div>
					</div>
					<div class="actions">
						<button type="submit" class="btn btn-outline btn-success">Salvar</button>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/sub_types/edit.html.erb
<%= link_to sub_types_path,class:"btn btn-outline btn-success pull-right topHeader", type:"button" do %>
  <i class="fa fa-clipboard fa-fw"></i> Voltar
<% end %>   
<%= link_to @sub_type,class:"btn btn-outline btn-success pull-right topHeader", type:"button" do %>
  <i class="fa fa-clipboard fa-fw"></i> Exibir
<% end %>
<h1  class="page-header topHeader">Editando Sub Cateoria</h1>

<%= render 'form' %>

app/views/sub_types/index.html.erb
<h1 class="page-header topHeader">Listando Sub-categoria
		<%= link_to equipaments_path,class:"btn btn-default dropdown-toggle pull-right", type:"button" do %>
		Voltar para Equipameto ou Acessorios  
		<% end %>
</h1>

<div class="panel panel-default">
	<div class="panel-heading">
		<strong>Lista de Sub-categorias</strong>
				<%= link_to new_sub_type_path,class:"btn btn-success dropdown-toggle pull-right botton-barra", type:"button" do %>
				Nova Sub-categoria  
		<% end %>
	</div>

	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-hover">
				<thead>
					<tr>
						<th>Sub-categoria</th>
						<th>Categoria</th>
						<th colspan="1" style="width: 5%"></th>
					</tr>
				</thead>

				<tbody>
					<% @sub_types.each do |sub_type| %>
					<tr>
						<td><%= sub_type.name_sub_type %></td>
						<td><%= sub_type.type_equipament.name_type %></td>
						<td><!--<#%= link_to sub_type,class:"btn btn-default btn-sm ", type:"button",title:"Exibir" do %>
									<i class="fa fa-search"></i>
								<#% end %>--> 
								<%= link_to edit_sub_type_path(sub_type),class:"btn btn-default btn-sm ", type:" button",title:"Editar" do %>
									<i class="fa fa-edit"></i>
								<% end %>
						</td>
						<!--td><#%= link_to 'Destroy', sub_type, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
					</tr>
			<% end %>
		</tbody>
	</table>
</div>
<br>

app/views/sub_types/new.html.erb
<%= link_to sub_types_path,class:"btn btn-outline btn-success pull-right topHeader", type:"button" do %>
  <i class="fa fa-clipboard fa-fw"></i> Voltar
<% end %>

<h1 class="page-header topHeader">Novo Periodo</h1>

<%= render 'form' %>

app/views/sub_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name Sub-categoria:</strong>
  <%= @sub_type.name_sub_type %>
</p>

<%= link_to 'Edit', edit_sub_type_path(@sub_type) %> |
<%= link_to 'Back', sub_types_path %>